const users = [
  {
    fullName: "John Doe",
    state: "SP",
    dateOfBirth: new Date("1990-01-15"),
    cpf: "123.456.789-09",
    email: "johndoe@example.com",
    password: "StrongP@ssw0rd",
    confirmPassword: "StrongP@ssw0rd",
    receivePromotionalInfo: true,
  },
  {
    fullName: "Jane Smith",
    state: "RJ",
    dateOfBirth: new Date("1985-05-20"),
    cpf: "987.654.321-00",
    email: "janesmith@example.com",
    password: "SecurePwd123!",
    confirmPassword: "SecurePwd123!",
    receivePromotionalInfo: false,
  },
  {
    fullName: "Alice Johnson",
    state: "MG",
    dateOfBirth: new Date("1992-08-10"),
    cpf: "456.789.123-45",
    email: "alice@example.com",
    password: "P@ssw0rd123",
    confirmPassword: "P@ssw0rd123",
    receivePromotionalInfo: true,
  },
  {
    fullName: "Bob Williams",
    state: "BA",
    dateOfBirth: new Date("1988-11-25"),
    cpf: "333.222.111-00",
    email: "bob@example.com",
    password: "BobPwd456!",
    confirmPassword: "BobPwd456!",
    receivePromotionalInfo: false,
  },
  {
    fullName: "Eva Martinez",
    state: "PR",
    dateOfBirth: new Date("1995-03-05"),
    cpf: "777.888.999-22",
    email: "eva@example.com",
    password: "EvaStrongPwd789",
    confirmPassword: "EvaStrongPwd789",
    receivePromotionalInfo: true,
  },
];
